In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [3]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

### Feature Extraction

> Since both the datasets are speaking about the same movies, now we will be merging both the datasets based on their 'movie IDs' or their 'title'

In [4]:
df = pd.merge(movies, credits, left_on='id', right_on='movie_id')
print(f"MOVIES DATA : {movies.shape}")
print(f"CREDITS DATA : {credits.shape}")
print(f"MERGED DATA : {df.shape}")
df.head()

MOVIES DATA : (4803, 20)
CREDITS DATA : (4803, 4)
MERGED DATA : (4803, 24)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Doing feature selection

In [5]:
df.columns.tolist()

['budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title_x',
 'vote_average',
 'vote_count',
 'movie_id',
 'title_y',
 'cast',
 'crew']

In [6]:
print(df['original_language'].nunique())
print(df['original_language'].value_counts())

37
original_language
en    4505
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
cn      12
ko      11
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
id       2
cs       2
ta       2
ro       2
ar       2
te       1
hu       1
xx       1
af       1
is       1
tr       1
vi       1
pl       1
nb       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [7]:
df['original_title'].head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: original_title, dtype: object

Features to be dropped : 
- budget
- homepage
- original_language : as englisgh language is dominating over all other languages
- original_title
- production_countries
- release_date
- revenue
- popularity
- runtime
- spoken_languages
- status
- tagline
- vote_average
- vote_count

### Feature Selection

In [8]:
dropped_columns = [
    'budget', 'homepage', 'original_language', 'original_title', 
    'production_countries', 'production_companies', 'release_date', 
    'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 
    'vote_average', 'vote_count', 'title_y','movie_id', 'popularity'
]

df.drop(columns=dropped_columns, inplace=True, errors='ignore')
# "Drop these columns if they exist. If they are already gone, just ignore them and move on."
# errors = 'ignore' is best for re-running a code block which has already been run before

print(df.shape)
print(df.columns)
df.head()

(4803, 7)
Index(['genres', 'id', 'keywords', 'overview', 'title_x', 'cast', 'crew'], dtype='object')

,genres,id,keywords,overview,title_x,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Changing Feature Names

In [9]:
# df.rename(columns={
#     'title_x': 'TITLE',
#     'id' : 'ID',
#     'keywords':'KEYWORDS',
# }, inplace=True)


cls = df.columns.str.upper()

for i, j in zip(cls, df.columns):
    df.rename(columns={j:i}, inplace=True)

df.rename(columns={'TITLE_X' : 'TITLE'}, inplace=True)

df = df[['ID','TITLE','OVERVIEW','GENRES','KEYWORDS','CAST','CREW']]

df

,ID,TITLE,OVERVIEW,GENRES,KEYWORDS,CAST,CREW
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

### Checking for Missing Values

In [10]:
print(df.isna().sum())
df.dropna(inplace=True)
print(df.isna().sum())

ID          0
TITLE       0
OVERVIEW    3
GENRES      0
KEYWORDS    0
CAST        0
CREW        0
dtype: int64
ID          0
TITLE       0
OVERVIEW    0
GENRES      0
KEYWORDS    0
CAST        0
CREW        0
dtype: int64

**Observation :** 3 missing samples found and hence removed

### Checking for Duplicates

In [11]:
df.duplicated().sum()

np.int64(0)

**Observation :** No Duplicates found

### Formatting of features

In [12]:
print(df.iloc[0]['GENRES'])
print(df.iloc[0]['KEYWORDS'])
print(df.iloc[0]['CAST'])
print(df.iloc[0]['CREW'])

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]
[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch's Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]

As we can above the above four features are in a list of multiple dictionaries format, hene we have to convert them into a proper format.

In [13]:
type(df.iloc[0]['GENRES'])

str

As you can clearly see, the 'GENRES' is in list format but its type not in string format, So first we have to convert it into a list format.

In [14]:
import ast

# for GENRE, KEYWORD
def converter(obj):
    temp = []

    for i in ast.literal_eval(obj):
        temp.append(i['name'])
    return temp

# for CAST
def converter2(obj):
    temp=[]
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            temp.append(i['name'])
            count += 1
        else:
            break
    return temp

# for CREW
def converter3(obj):
    temp = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            temp.append(i['name'])
            break
    return temp

- **GENRES  :** tell about from which genre the movie belongs
- **KEYWORDS :** keywords used to search the movie
- **CAST :** actors hired for the movie
    - For the cast we will only take the first 3 actors name, bcoz in most of the movie top actors names are mentioned first and rest of the cast is not so much important
- **CREW :** crew hired for the movie
    - We are only taking only where there is a director name used, coz directore name also influences the movie

In [15]:
df['GENRES'] = df['GENRES'].apply(converter)
df['KEYWORDS'] = df['KEYWORDS'].apply(converter)
df['CAST'] = df['CAST'].apply(converter2)
df['CREW'] = df['CREW'].apply(converter3)

df['CREW']

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4798     [Robert Rodriguez]
4799         [Edward Burns]
4800          [Scott Smith]
4801          [Daniel Hsia]
4802     [Brian Herzlinger]
Name: CREW, Length: 4800, dtype: object

In [16]:
df['CREW'].isna().sum()

np.int64(0)

### Converting overview into a columns

In [17]:
df['OVERVIEW']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: OVERVIEW, Length: 4800, dtype: object

### Converting OVERVIEW into a List

In [18]:
df['OVERVIEW'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [19]:
df['OVERVIEW'] = df['OVERVIEW'].apply(lambda x:x.split())
df['OVERVIEW'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

### Removing all the Spaces btwn words from OVERVIEW, GENRES, KEYWORDS, CAST, CREW

In [20]:
df['OVERVIEW'] = df['OVERVIEW'].apply(lambda x : [i.replace(" ", "") for i in x])
df['GENRES'] = df['GENRES'].apply(lambda x : [i.replace(" ", "") for i in x])
df['KEYWORDS'] = df['KEYWORDS'].apply(lambda x : [i.replace(" ", "") for i in x])
df['CAST'] = df['CAST'].apply(lambda x : [i.replace(" ", "") for i in x])
df['CREW'] = df['CREW'].apply(lambda x : [i.replace(" ", "") for i in x])

In [21]:
df.head()

,ID,TITLE,OVERVIEW,GENRES,KEYWORDS,CAST,CREW
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

**Observation :** Suppose there are two people as Sam Altman, and Sam Robert. If I type Sam the computer will get confused and cant differentiate btwn the both. So if we remove the space and consider it as one word, then the computer will be able to differentiate btwn the both.

### Making a Specific Feature called 'TAGS' and Concanating all five above features

In [22]:
df['TAGS'] = df['OVERVIEW'] + df['GENRES'] + df['KEYWORDS'] + df['CAST'] + df['CREW']
df.head()

,ID,TITLE,OVERVIEW,GENRES,KEYWORDS,CAST,CREW,TAGS
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

Now removing the useless features

In [23]:
df = df[['ID','TITLE','TAGS']]
df.head()

,ID,TITLE,TAGS
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [24]:
df['TAGS'].head()

0    [In, the, 22nd, century,, a, paraplegic, Marin...
1    [Captain, Barbossa,, long, believed, to, be, d...
2    [A, cryptic, message, from, Bond’s, past, send...
3    [Following, the, death, of, District, Attorney...
4    [John, Carter, is, a, war-weary,, former, mili...
Name: TAGS, dtype: object

Joining the TAGS elements with spaces

In [25]:
df['TAGS'] = df['TAGS'].apply(lambda x: " ".join(x))
df['TAGS']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: TAGS, Length: 4800, dtype: object

In [26]:
df['TAGS'] = df['TAGS'].apply(lambda x:x.lower())
df['TAGS'].head()

0    in the 22nd century, a paraplegic marine is di...
1    captain barbossa, long believed to be dead, ha...
2    a cryptic message from bond’s past sends him o...
3    following the death of district attorney harve...
4    john carter is a war-weary, former military ca...
Name: TAGS, dtype: object

In [27]:
df['TAGS'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

**Overview :** Here we have combined OVERVIEW, GENRES, KEYWORDS, CAST, CREW, and converted them into lower case.

### Using CountVectorizer

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

# by default vectorizer returns a sparse output, hence we will be converting it into an array
print(cv.fit_transform(df['TAGS']).toarray().shape)
vector = cv.fit_transform(df['TAGS']).toarray()
vector

(4800, 5000)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Observation :** By this we have converted every movie into a vector form.

In [29]:
print(vector[0])
cv.get_feature_names_out().tolist()    # by this we can print the names of all the features

[0 0 0 ... 0 0 0]

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcentury',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'bid',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikers',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'buddycop',
 'budget',
 'build',
 'building',
 'builds',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'burned',
 'burns',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'canine',
 'cannibal',
 'canuxploitation',
 'capable',
 'caper',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confederate',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'congress',
 'conman',
 'connected',
 'connecticut',
 'connection',
 'connections',
 'connects',
 'connell',
 'connie',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'containing',
 'contains',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 ...]

### Removing the Similar Words

To do so we will be applying **Stemming**.

For eg, multiple words like loved, loving, loves will be replaed with only one word like love.

In [30]:
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(txt):
    y = []
    for i in txt.split():
        y.append(ps.stem(i))
    return " ".join(y)

ModuleNotFoundError: No module named 'nltk'

In [ ]:
print(ps.stem('dancing'))
print(ps.stem('loving'))

danc
love

In [ ]:
df['TAGS'] = df['TAGS'].apply(stem)
df['TAGS']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4798    el mariachi just want to play hi guitar and ca...
4799    a newlyw couple' honeymoon is upend by the arr...
4800    "signed, sealed, delivered" introduc a dedic q...
4801    when ambiti new york attorney sam is sent to s...
4802    ever sinc the second grade when he first saw h...
Name: TAGS, Length: 4800, dtype: str

### Choosing the Distance to be used for vector movies

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
print(len(cosine_similarity(vector).shape))
cosine_similarity(vector)

2

array([[1.        , 0.08980265, 0.05986843, ..., 0.02512595, 0.02635231,
        0.        ],
       [0.08980265, 1.        , 0.06451613, ..., 0.02707652, 0.        ,
        0.        ],
       [0.05986843, 0.06451613, 1.        , ..., 0.02707652, 0.        ,
        0.        ],
       ...,
       [0.02512595, 0.02707652, 0.02707652, ..., 1.        , 0.07150969,
        0.0489116 ],
       [0.02635231, 0.        , 0.        , ..., 0.07150969, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.0489116 , 0.05129892,
        1.        ]], shape=(4800, 4800))

**Observation :** Here we have chose Cosine similarity distance instead of Euclidean distanace bcoz, euclidean distance fails in high dimensional data.

- Higher the distance higher will be the dis-similarity btwn the movies.

- Euclidean distance takes the distance btwn two points, but Euclidean distance takes the degree as their distance. Higher the degree higher the dis-similarity btwn the movies.

In [ ]:
# storing the similarity in an object
similarity = cosine_similarity(vector)
print(similarity[0].tolist() )          # printing the similarity of the first movie with the rest of the movies
print(sorted(similarity[0].tolist(), reverse=True))

[1.0000000000000002, 0.08980265101338746, 0.05986843400892497, 0.03955938860646177, 0.1800205749557739, 0.11669000700233413, 0.022680460581325723, 0.17391639824998364, 0.0629940788348712, 0.07537783614444091, 0.1160517706371319, 0.08006407690254357, 0.09622504486493762, 0.04714045207910317, 0.1126872339638022, 0.050832856777534886, 0.08111071056538127, 0.1481668148335556, 0.11135885079684349, 0.08466675133346033, 0.05735393346764043, 0.09128709291752768, 0.06666666666666667, 0.09622504486493762, 0.05555555555555555, 0.03823595564509362, 0.16666666666666669, 0.19245008972987526, 0.12379689211803457, 0.07071067811865475, 0.07216878364870322, 0.15748519708717798, 0.08989331499509895, 0.10425720702853739, 0.0, 0.11180339887498947, 0.1917988185229168, 0.08333333333333333, 0.062017367294604234, 0.08703882797784893, 0.05555555555555555, 0.14433756729740646, 0.0, 0.09622504486493763, 0.04042260417272216, 0.0890870806374748, 0.17407765595569785, 0.21339479988815996, 0.0668153104781061, 0.06189844605901729, 0.11973686801784994, 0.08535791995526398, 0.1714985851425088, 0.05143444998736397, 0.034752402342845795, 0.07749842582921285, 0.14213381090374028, 0.028583097523751468, 0.046676002800933654, 0.07911877721292354, 0.02817180849095055, 0.22360679774997894, 0.08084520834544431, 0.09072184232530289, 0.030949223029508643, 0.020833333333333332, 0.02457365935914952, 0.17960530202677488, 0.13074409009212268, 0.05076730825668096, 0.08574929257125441, 0.08111071056538127, 0.1217161238900369, 0.03726779962499649, 0.22613350843332272, 0.09128709291752768, 0.07715167498104596, 0.014617633655117155, 0.053376051268362375, 0.07624928516630233, 0.034020690871988585, 0.11547005383792512, 0.08219949365267865, 0.2187974872468418, 0.14360673947588817, 0.10482848367219183, 0.08838834764831843, 0.1160517706371319, 0.09128709291752768, 0.06085806194501845, 0.06415002990995841, 0.15748519708717798, 0.07001400420140048, 0.050251890762960605, 0.16343011261515333, 0.12422599874998833, 0.08838834764831843, 0.07453559924999299, 0.08219949365267865, 0.029012942659282975, 0.07273929674533079, 0.08703882797784893, 0.11037769642208699, 0.08753762190648169, 0.05802588531856595, 0.10660035817780521, 0.044151078568834795, 0.08989331499509895, 0.16666666666666666, 0.07856742013183862, 0.02457365935914952, 0.15214515486254612, 0.09284766908852593, 0.05270462766947299, 0.05143444998736397, 0.05407380704358751, 0.0563436169819011, 0.06085806194501845, 0.017376201171422898, 0.048621663832631515, 0.0, 0.08838834764831843, 0.09622504486493762, 0.12155415958157878, 0.06741998624632421, 0.07909649964604158, 0.11433239009500587, 0.13471506281091264, 0.0, 0.10411584125907071, 0.0314970394174356, 0.1111111111111111, 0.046225016352102424, 0.032075014954979206, 0.13333333333333333, 0.0, 0.025416428388767443, 0.034020690871988585, 0.08111071056538127, 0.10669739994407998, 0.050251890762960605, 0.11180339887498947, 0.08838834764831843, 0.06868028197434452, 0.05479966243511909, 0.0222717701593687, 0.017010345435994292, 0.06085806194501845, 0.10425720702853739, 0.17071583991052797, 0.18750000000000003, 0.20211302086361077, 0.0629940788348712, 0.08466675133346033, 0.03268602252303067, 0.0, 0.06622661785325219, 0.10206207261596575, 0.15075567228888181, 0.06666666666666667, 0.09558988911273406, 0.034752402342845795, 0.03553345272593507, 0.05270462766947299, 0.09128709291752768, 0.049690399499995326, 0.1178511301977579, 0.06804138174397717, 0.15617376188860607, 0.11785113019775792, 0.09072184232530289, 0.029012942659282975, 0.14907119849998596, 0.024310831916315757, 0.10959932487023819, 0.050832856777534886, 0.030429030972509225, 0.0, 0.025717224993681984, 0.07647191129018724, 0.022893427324781505, 0.023338001400466827, 0.10675210253672475, 0.07362101738323101, 0.1800205749557739, 0.05479966243511909, 0.04042260417272216, 0.1388888888888889, 0.022473328748774737, 0.08084520834544431, 0.08268982305947231, 0.05143444998736397, 0.0, 0.08679260732054925, 0.0, 0.06415002990995841, 0.05802588531856595, 0.048621663832631515, 0.05892556509887895, 0.11446713662390752, 0.07856742013183862, 0.0, 0.034020690871988585, 0.08703882797784893, 0.025416428388767443, 0.08084520834544431, 0.11669000700233413, 0.08451542547285165, 0.16666666666666666, 0.03553345272593507, 0.052057920629535355, 0.027036903521793755, 0.07537783614444091, 0.06454972243679027, 0.028583097523751468, 0.07293249574894728, 0.06415002990995841, 0.045360921162651446, 0.041666666666666664, 0.06537204504606134, 0.18569533817705186, 0.024310831916315757, 0.0890870806374748, 0.08219949365267865, 0.0625, 0.052057920629535355, 0.029462782549439476, 0.09128709291752768, 0.1256297269074015, 0.07802743146408704, 0.0890870806374748, 0.0, 0.1178511301977579, 0.10910894511799618, 0.06741998624632421, 0.05986843400892497, 0.09622504486493762, 0.06950480468569159, 0.11867816581938531, 0.1058334391668254, 0.050251890762960605, 0.08333333333333333, 0.09284766908852593, 0.09829463743659808, 0.06189844605901729, 0.08980265101338746, 0.06509445549041193, 0.0, 0.046225016352102424, 0.14213381090374028, 0.0, 0.041666666666666664, 0.022473328748774737, 0.06741998624632421, 0.08219949365267865, 0.0, 0.08084520834544431, 0.08574929257125441, 0.023112508176051212, 0.0629940788348712, 0.24759378423606915, 0.025125945381480302, 0.07142857142857142, 0.10425720702853739, 0.0, 0.029012942659282975, 0.10959932487023819, 0.07273929674533079, 0.027036903521793755, 0.03268602252303067, 0.10050378152592121, 0.07808688094430304, 0.029934217004462485, 0.024310831916315757, 0.0798188571017626, 0.1217161238900369, 0.06804138174397717, 0.06509445549041193, 0.1256297269074015, 0.10286889997472794, 0.0, 0.07216878364870322, 0.029934217004462485, 0.0, 0.0200643088476282, 0.022680460581325723, 0.022075539284417398, 0.027036903521793755, 0.0, 0.04914731871829904, 0.06537204504606134, 0.05555555555555555, 0.1, 0.0314970394174356, 0.1178511301977579, 0.10814761408717502, 0.03984095364447979, 0.048112522432468816, 0.0, 0.041030496993110906, 0.18220272220337375, 0.1805787796286538, 0.05802588531856595, 0.029462782549439476, 0.07106690545187014, 0.19050019050028574, 0.09284766908852593, 0.10314212462587934, 0.06950480468569159, 0.06537204504606134, 0.03533326266687867, 0.15430334996209188, 0.10959932487023819, 0.07856742013183862, 0.0, 0.09128709291752768, 0.0, 0.0, 0.0, 0.07106690545187014, 0.03268602252303067, 0.0, 0.22222222222222227, 0.03268602252303067, 0.026028960314767677, 0.10910894511799618, 0.05892556509887895, 0.028583097523751468, 0.0, 0.08219949365267865, 0.10959932487023819, 0.049690399499995326, 0.14291548761875733, 0.029934217004462485, 0.10540925533894598, 0.05479966243511909, 0.07273929674533079, 0.023809523809523808, 0.0, 0.0563436169819011, 0.052057920629535355, 0.06085806194501845, 0.13382584475782766, 0.022473328748774737, 0.030949223029508643, 0.023112508176051212, 0.0, 0.0, 0.06537204504606134, 0.09128709291752768, 0.053376051268362375, 0.0, 0.029012942659282975, 0.023338001400466827, 0.0, 0.03955938860646177, 0.09128709291752768, 0.0, 0.06415002990995841, 0.034020690871988585, 0.0, 0.0563436169819011, 0.09622504486493762, 0.08989331499509895, 0.025717224993681984, 0.08006407690254357, 0.05892556509887895, 0.0, 0.13333333333333333, 0.09284766908852593, 0.05555555555555555, 0.10166571355506977, 0.05270462766947299, 0.17766726362967533, 0.043396303660274624, 0.04267895997763199, 0.048112522432468816, 0.0, 0.0, 0.05270462766947298, 0.027777777777777776, 0.0890870806374748, 0.0, 0.050832856777534886, 0.032075014954979206, 0.0, 0.023112508176051212, 0.027036903521793755, 0.0, 0.09805806756909201, 0.027399831217559546, 0.0601929265428846, 0.030949223029508643, 0.0, 0.025717224993681984, 0.0563436169819011, 0.023338001400466827, 0.05479966243511909, 0.0, 0.025416428388767443, 0.10206207261596575, 0.032075014954979206, 0.06189844605901729, 0.10849075915068657, 0.06537204504606134, 0.029934217004462485, 0.021516574145596757, 0.026028960314767677, 0.03553345272593507, 0.0, 0.10050378152592121, 0.05802588531856595, 0.10050378152592121, 0.1388888888888889, 0.032075014954979206, 0.07027283689263064, 0.05555555555555555, 0.034020690871988585, 0.036369648372665396, 0.07537783614444091, 0.1270821419438372, 0.0, 0.14547859349066158, 0.05143444998736397, 0.03984095364447979, 0.07001400420140048, 0.060633906259083235, 0.029012942659282975, 0.059339082909692656, 0.0, 0.052057920629535355, 0.025717224993681984, 0.12286829679574761, 0.03268602252303067, 0.0, 0.03928371006591931, 0.0, 0.028583097523751468, 0.02817180849095055, 0.030429030972509225, 0.02817180849095055, 0.029934217004462485, 0.048112522432468816, 0.057166195047502935, 0.0, 0.02817180849095055, 0.025717224993681984, 0.023570226039551584, 0.025416428388767443, 0.05802588531856595, 0.026028960314767677, 0.025717224993681984, 0.0314970394174356, 0.026352313834736494, 0.1228682967957476, 0.025416428388767443, 0.06933752452815364, 0.08574929257125441, 0.046676002800933654, 0.03553345272593507, 0.02817180849095055, 0.1911797782254681, 0.0, 0.034752402342845795, 0.0, 0.0, 0.20851441405707477, 0.08989331499509895, 0.029934217004462485, 0.07001400420140048, 0.048621663832631515, 0.08219949365267865, 0.08333333333333333, 0.10166571355506977, 0.0, 0.06741998624632421, 0.10425720702853739, 0.0, 0.03901371573204352, 0.09435641951204964, 0.052057920629535355, 0.0, 0.029934217004462485, 0.12830005981991682, 0.034020690871988585, 0.0563436169819011, 0.05773502691896257, 0.13900960937138318, 0.07500586006173493, 0.0, 0.14907119849998596, 0.08679260732054925, 0.06085806194501845, 0.01924500897298752, 0.0, 0.2132007163556104, 0.0, 0.0, 0.06950480468569159, 0.0, 0.027777777777777776, 0.08679260732054925, 0.15075567228888181, 0.08111071056538127, 0.0, 0.14547859349066158, 0.03553345272593507, 0.24720661623652207, 0.11433239009500587, 0.025125945381480302, 0.10411584125907071, 0.0944911182523068, 0.05986843400892497, 0.1111111111111111, 0.057166195047502935, 0.027036903521793755, 0.025416428388767443, 0.0, 0.05407380704358751, 0.0, 0.0, 0.028583097523751468, 0.0, 0.05143444998736397, 0.0, 0.02457365935914952, 0.0, 0.0, 0.024845199749997663, 0.1270821419438372, 0.1, 0.050251890762960605, 0.022680460581325723, 0.06950480468569159, 0.08333333333333333, 0.10814761408717502, 0.07624928516630233, 0.06950480468569159, 0.0, 0.25724787771376323, 0.05479966243511909, 0.08989331499509895, 0.03984095364447979, 0.07715167498104596, 0.05986843400892497, 0.02817180849095055, 0.06537204504606134, 0.08703882797784893, 0.0, 0.12422599874998831, 0.02817180849095055, 0.044151078568834795, 0.0, 0.032075014954979206, 0.0, 0.049029033784546004, 0.028583097523751468, 0.14506471329641488, 0.0, 0.032075014954979206, 0.04578685464956301, 0.036369648372665396, 0.0, 0.027036903521793755, 0.1, 0.045360921162651446, 0.02457365935914952, 0.029934217004462485, 0.14291548761875733, 0.023809523809523808, 0.07453559924999298, 0.021698151830137312, 0.08466675133346033, 0.0222717701593687, 0.024056261216234408, 0.0563436169819011, 0.028583097523751468, 0.15214515486254612, 0.047619047619047616, 0.1217161238900369, 0.024845199749997663, 0.16037507477489604, 0.23809523809523808, 0.050832856777534886, 0.048112522432468816, 0.0, 0.044946657497549475, 0.07808688094430304, 0.028583097523751468, 0.09724332766526303, 0.034752402342845795, 0.07715167498104596, 0.026352313834736494, 0.0, 0.05479966243511909, 0.13344012817090595, 0.09622504486493763, 0.057166195047502935, 0.03928371006591931, 0.03316790634033297, 0.07142857142857142, 0.036588086663230115, 0.0445435403187374, 0.05555555555555555, 0.06950480468569159, 0.0, 0.0, 0.06401843996644799, 0.0, 0.04714045207910317, 0.05976143046671968, 0.02457365935914952, 0.07001400420140048, 0.03823595564509362, 0.05892556509887895, 0.03268602252303067, 0.0, 0.05479966243511909, 0.09724332766526303, 0.0, 0.0, 0.06950480468569159, 0.022075539284417398, 0.0, 0.12126781251816647, 0.0314970394174356, 0.08980265101338746, 0.11470786693528086, 0.0, 0.049690399499995326, 0.025416428388767443, 0.027036903521793755, 0.08111071056538127, 0.023570226039551584, 0.08574929257125441, 0.07453559924999299, 0.02817180849095055, 0.052057920629535355, 0.03553345272593507, 0.0, 0.050251890762960605, 0.0, 0.0, 0.10540925533894598, 0.057166195047502935, 0.047619047619047616, 0.05555555555555555, 0.05143444998736397, 0.032075014954979206, 0.0, 0.0, 0.0, 0.024310831916315757, 0.12126781251816647, 0.08830215713766959, 0.025416428388767443, 0.0, 0.03681050869161551, 0.05270462766947299, 0.026688025634181187, 0.10206207261596575, 0.16798421022632318, 0.0, 0.0, 0.06415002990995841, 0.07715167498104596, 0.05143444998736397, 0.0, 0.06950480468569159, 0.03553345272593507, 0.017471413945365305, 0.053376051268362375, 0.05802588531856595, 0.022473328748774737, 0.07624928516630233, 0.050832856777534886, 0.03268602252303067, 0.027036903521793755, 0.06085806194501845, 0.0, 0.08111071056538127, 0.034020690871988585, 0.023809523809523808, 0.050251890762960605, 0.0, 0.03726779962499649, 0.0, 0.1160517706371319, 0.049690399499995326, 0.0, 0.029012942659282975, 0.1, 0.11904761904761904, 0.0, 0.022473328748774737, 0.06804138174397717, 0.0, 0.0, 0.023338001400466827, 0.0, 0.030429030972509225, 0.0629940788348712, 0.023809523809523808, 0.020672455764868078, 0.07293249574894728, 0.025125945381480302, 0.026028960314767677, 0.0, 0.024845199749997663, 0.0, 0.0445435403187374, 0.06537204504606134, 0.0, 0.027036903521793755, 0.0, 0.10425720702853739, 0.034752402342845795, 0.0, 0.04578685464956301, 0.0, 0.027036903521793755, 0.03268602252303067, 0.0, 0.026028960314767677, 0.025416428388767443, 0.0, 0.0, 0.03594425773447947, 0.07453559924999299, 0.0, 0.018871283902409927, 0.05407380704358751, 0.07715167498104596, 0.044151078568834795, 0.04914731871829904, 0.048621663832631515, 0.032075014954979206, 0.07905694150420949, 0.0, 0.03823595564509362, 0.1301448015738384, 0.05802588531856595, 0.03333333333333333, 0.025416428388767443, 0.06666666666666667, 0.06189844605901729, 0.08574929257125441, 0.023338001400466827, 0.03823595564509362, 0.0, 0.050251890762960605, 0.03726779962499649, 0.08333333333333333, 0.029012942659282975, 0.13344012817090595, 0.06154574548966636, 0.029934217004462485, 0.027399831217559546, 0.025416428388767443, 0.0, 0.0, 0.029462782549439476, 0.032075014954979206, 0.0, 0.030429030972509225, 0.0, 0.0, 0.049690399499995326, 0.06509445549041193, 0.03268602252303067, 0.048621663832631515, 0.0, 0.0, 0.10910894511799618, 0.0445435403187374, 0.08980265101338746, 0.08333333333333333, 0.11340230290662862, 0.12858612496840993, 0.0, 0.0, 0.10206207261596575, 0.07453559924999299, 0.034020690871988585, 0.07715167498104596, 0.0975342893301088, 0.08838834764831843, 0.08451542547285165, 0.05143444998736397, 0.0, 0.07001400420140048, 0.1, 0.05802588531856595, 0.05555555555555555, 0.09284766908852593, 0.023338001400466827, 0.03823595564509362, 0.0, 0.0, 0.09259259259259259, 0.07856742013183862, 0.0, 0.0, 0.04914731871829904, 0.052057920629535355, 0.05892556509887895, 0.048621663832631515, 0.053376051268362375, 0.12126781251816647, 0.022680460581325723, 0.028583097523751468, 0.022680460581325723, 0.09072184232530289, 0.10050378152592121, 0.08838834764831843, 0.023112508176051212, 0.0445435403187374, 0.027399831217559546, 0.032075014954979206, 0.0, 0.01756820922315766, 0.018294043331615058, 0.0222717701593687, 0.06189844605901729, 0.0, 0.0, 0.03553345272593507, 0.07537783614444091, 0.027777777777777776, 0.0, 0.029934217004462485, 0.049690399499995326, 0.027399831217559546, 0.049690399499995326, 0.049690399499995326, 0.027036903521793755, 0.0668153104781061, 0.028583097523751468, 0.16666666666666666, 0.0, 0.06189844605901729, 0.026028960314767677, 0.0, 0.06085806194501845, 0.06085806194501845, 0.0, 0.0, 0.05780733130160799, 0.05892556509887897, 0.0, 0.08084520834544431, 0.0, 0.022473328748774737, 0.0314970394174356, 0.1126872339638022, 0.027399831217559546, 0.025717224993681984, 0.0, 0.04042260417272216, 0.1178511301977579, 0.017282528245507085, 0.044151078568834795, 0.028583097523751468, 0.03268602252303067, 0.04578685464956301, 0.0, 0.041666666666666664, 0.0, 0.02457365935914952, 0.030949223029508643, 0.10166571355506977, 0.028583097523751468, 0.0, 0.046225016352102424, 0.027036903521793755, 0.05479966243511909, 0.0, 0.0, 0.034752402342845795, 0.0, 0.03268602252303067, 0.0, 0.029462782549439476, 0.029012942659282975, 0.0, 0.08333333333333333, 0.022680460581325723, 0.055901699437494734, 0.050251890762960605, 0.07106690545187014, 0.0, 0.0445435403187374, 0.0, 0.019920476822239894, 0.08980265101338746, 0.0, 0.0, 0.050251890762960605, 0.10540925533894598, 0.08703882797784893, 0.1126872339638022, 0.09284766908852593, 0.027399831217559546, 0.034020690871988585, 0.023112508176051212, 0.0, 0.0, 0.024310831916315757, 0.07808688094430304, 0.0, 0.023112508176051212, 0.024310831916315757, 0.03333333333333333, 0.0, 0.03553345272593507, 0.027036903521793755, 0.0, 0.030949223029508643, 0.0, 0.025125945381480302, 0.10206207261596575, 0.0, 0.0944911182523068, 0.0, 0.0, 0.020833333333333332, 0.0, 0.0, 0.0, 0.05555555555555555, 0.026352313834736494, 0.18898223650461357, 0.05143444998736397, 0.10050378152592121, 0.029934217004462485, 0.10425720702853739, 0.0, 0.08703882797784893, 0.0, 0.1270001270001905, 0.0, 0.032075014954979206, 0.20953951903123735, 0.0, 0.0, 0.06537204504606134, 0.026028960314767677, 0.0, 0.0, 0.0, 0.03984095364447979, 0.06804138174397717, 0.025717224993681984, 0.025125945381480302, 0.0, 0.02817180849095055, 0.05407380704358751, 0.034752402342845795, 0.0, 0.026352313834736494, 0.0944911182523068, 0.053376051268362375, 0.024845199749997663, 0.049690399499995326, 0.029934217004462485, 0.0, 0.0, 0.03928371006591931, 0.0, 0.044151078568834795, 0.0, 0.03333333333333333, 0.2166445612065605, 0.032075014954979206, 0.0, 0.0, 0.07624928516630233, 0.09284766908852593, 0.048621663832631515, 0.043768810953240846, 0.0, 0.030949223029508643, 0.016835875742536845, 0.0, 0.08111071056538127, 0.10675210253672475, 0.030429030972509225, 0.0, 0.034752402342845795, 0.046225016352102424, 0.03333333333333333, 0.0, 0.03928371006591931, 0.057166195047502935, 0.07372097807744857, 0.0629940788348712, 0.0, 0.0, 0.0, 0.13130643285972254, 0.050251890762960605, 0.09284766908852593, 0.07647191129018724, 0.027777777777777776, 0.06804138174397717, 0.0, 0.053376051268362375, 0.04042260417272216, 0.05555555555555555, 0.0, 0.0, 0.0, 0.13518451760896877, 0.034020690871988585, 0.025717224993681984, 0.07293249574894728, 0.10942202738310211, 0.05407380704358751, 0.043033148291193514, 0.0, 0.05270462766947299, 0.029012942659282975, 0.0, 0.0, 0.0944911182523068, 0.0445435403187374, 0.030949223029508643, 0.06741998624632421, 0.1160517706371319, 0.057166195047502935, 0.041666666666666664, 0.028583097523751468, 0.034020690871988585, 0.027399831217559546, 0.1270821419438372, 0.049690399499995326, 0.0, 0.0, 0.0, 0.0, 0.04714045207910317, 0.03333333333333333, 0.08084520834544431, 0.02817180849095055, 0.13074409009212268, 0.027399831217559546, 0.0, 0.0, 0.0, 0.032075014954979206, 0.02457365935914952, 0.0, 0.034752402342845795, 0.10540925533894598, 0.0, 0.0, 0.03615507630310936, 0.0, 0.05407380704358751, 0.03553345272593507, 0.0, 0.030949223029508643, 0.0314970394174356, 0.0, 0.025125945381480302, 0.034020690871988585, 0.0, 0.06189844605901729, 0.1800205749557739, 0.0, 0.06415002990995841, 0.0, 0.050251890762960605, 0.06666666666666667, 0.1, 0.0, 0.06415002990995841, 0.05479966243511909, 0.05555555555555555, 0.1111111111111111, 0.057166195047502935, 0.030429030972509225, 0.06950480468569159, 0.10411584125907071, 0.047619047619047616, 0.0563436169819011, 0.09820927516479827, 0.0, 0.0, 0.06666666666666667, 0.07142857142857142, 0.0, 0.0, 0.13333333333333333, 0.06537204504606134, 0.05892556509887895, 0.020998026278290397, 0.029934217004462485, 0.023338001400466827, 0.024310831916315757, 0.043033148291193514, 0.0445435403187374, 0.0, 0.04042260417272216, 0.030429030972509225, 0.0, 0.10411584125907071, 0.0, 0.018751465015433733, 0.04714045207910317, 

**Observation :** As you can clearly see in the list above, the max similarity is 1. It is bcoz a movie's similarity with itself will be the highest.

### Making a function where with one input movie will return five movies with max similarity

In [ ]:
def recommend(movie):
    movie_index = df[df['TITLE'] == movie].index[0]             # finds the index of the movie
    distances = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda x: x[1])
    
    for i in distances[1:6]:
        print(df.iloc[i[0]]['TITLE'])       # 'df' is the dataframe variable and 'TITLE' is the column name

In [ ]:
df[df['TITLE'] == 'Batman Begins'].index

Index([119], dtype='int64')

In [ ]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Independence Day
Aliens vs Predator: Requiem