In [3]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, confusion_matrix


import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_pickle("cleaned_online_retail.pkl")
print(df.shape)
df.head()

(406309, 8)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# **STEP 3 : FEATURE ENGINEERING**

In [6]:
# adding a new feature as 'Sales'
df['Sales'] = df['Quantity'] * df['Price']
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Sales
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [ ]:
# creating a new df with unique coustomer id
unique_df = df.groupby(by="Customer ID", as_index=False).agg(
        MonetaryValue = ("Sales", "sum"),
        Frequency = ("Invoice", "nunique"),
        LasInvoiceDate = ("InvoiceDate", "max")
    )


# as_index = False means we dont want to make customer id as index

unique_df.head()

   Customer ID  MonetaryValue  Frequency      LasInvoiceDate
0      12346.0         169.36          2 2010-06-28 13:53:00
1      12347.0        1323.32          2 2010-12-07 14:57:00
2      12348.0         221.16          1 2010-09-27 14:59:00
3      12349.0        2221.14          2 2010-10-28 08:23:00
4      12351.0         300.93          1 2010-11-29 15:23:00

In [11]:
unique_df.describe()

        Customer ID  MonetaryValue    Frequency                 LasInvoiceDate
count   4285.000000    4285.000000  4285.000000                           4285
mean   15356.806768    2024.126801     4.426138  2010-09-11 00:06:10.431738624
min    12346.000000       1.550000     1.000000            2009-12-01 10:49:00
25%    13891.000000     307.560000     1.000000            2010-07-27 14:39:00
50%    15362.000000     702.900000     2.000000            2010-10-19 12:10:00
75%    16840.000000    1704.290000     5.000000            2010-11-22 11:24:00
max    18287.000000  349164.350000   183.000000            2010-12-09 20:01:00
std     1699.839258    8813.945538     7.938017                            NaN