# **AQI**

In [248]:
import pandas as pd
import numpy as np





import warnings
warnings.filterwarnings('ignore')

In [249]:
df = pd.read_csv('london weather AQI.csv')
df.head(5)

,Unnamed: 0,dt,summery,probability_of_precipitation_unit(%),dt_txt,temprature_unit(K),pressure_unit(hPa),sea_level_pressure_unit(hPa),ground_level_pressure_unit(hPa),humidity_unit(%),cloudiness_unit(%),speed,degrees,direction,gust_speed_unit(meter/sec),part_of_day,visibility_distance
0,0,1771534800,"overcast clouds, 277.99K, feels like 275.27K, ...",0,2026-02-19 21:00:00,277.99,1010,1010,1008,90,100,3.27,300,West-Northwest,7.62,night,10000.0
1,1,1771545600,"overcast clouds, 277.71K, feels like 275.03K, ...",0,2026-02-20 00:00:00,277.71,1013,1013,1011,87,100,3.13,276,West,7.62,night,10000.0
2,2,1771556400,"overcast clouds, 277.42K, feels like 274.89K, ...",0,2026-02-20 03:00:00,277.42,1017,1017,1012,87,100,2.86,248,West-Southwest,8.56,night,10000.0
3,3,1771567200,"overcast clouds, 278.79K, feels like 276.37K, ...",0,2026-02-20 06:00:00,278.79,1018,1018,1013,89,100,3.08,229,Southwest,9.26,night,10000.0
4,4,1771578000,"overcast clouds, 279.68K, feels like 276.84K, ...",0,2026-02-20 09:00:00,279.68,1018,1018,1014,80,100,4.09,218,Southwest,11.92,day,10000.0

In [250]:

# checking for null values
print(df.isna().sum())

Unnamed: 0                              0
dt                                      0
summery                                 0
probability_of_precipitation_unit(%)    0
dt_txt                                  0
temprature_unit(K)                      0
pressure_unit(hPa)                      0
sea_level_pressure_unit(hPa)            0
ground_level_pressure_unit(hPa)         0
humidity_unit(%)                        0
cloudiness_unit(%)                      0
speed                                   0
degrees                                 0
direction                               0
gust_speed_unit(meter/sec)              0
part_of_day                             0
visibility_distance                     0
dtype: int64

In [251]:
print(df.columns)
cols = df.columns

Index(['Unnamed: 0', 'dt', 'summery', 'probability_of_precipitation_unit(%)',
       'dt_txt', 'temprature_unit(K)', 'pressure_unit(hPa)',
       'sea_level_pressure_unit(hPa)', 'ground_level_pressure_unit(hPa)',
       'humidity_unit(%)', 'cloudiness_unit(%)', 'speed', 'degrees',
       'direction', 'gust_speed_unit(meter/sec)', 'part_of_day',
       'visibility_distance'],
      dtype='object')

In [252]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 17 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            40 non-null     int64
 1   dt                                    40 non-null     int64
 2   summery                               40 non-null     object
 3   probability_of_precipitation_unit(%)  40 non-null     int64
 4   dt_txt                                40 non-null     object
 5   temprature_unit(K)                    40 non-null     float64
 6   pressure_unit(hPa)                    40 non-null     int64
 7   sea_level_pressure_unit(hPa)          40 non-null     int64
 8   ground_level_pressure_unit(hPa)       40 non-null     int64
 9   humidity_unit(%)                      40 non-null     int64
 10  cloudiness_unit(%)                    40 non-null     int64
 11  speed                                 40 non-null     float64
 12  degrees                               40 non-null     int64
 13  direction                             40 non-null     object
 14  gust_speed_unit(meter/sec)            40 non-null     float64
 15  part_of_day                           40 non-null     object
 16  visibility_distance                   40 non-null     float64
dtypes: float64(4), int64(9), object(4)
memory usage: 5.4+ KB

In [253]:
# converting dt_txt into date time format

df['dt_txt'] = pd.to_datetime(df['dt_txt'])
print(df['dt_txt'].info())

df['dt_txt']

<class 'pandas.core.series.Series'>
RangeIndex: 40 entries, 0 to 39
Series name: dt_txt
Non-Null Count  Dtype
--------------  -----
40 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 452.0 bytes
None

0    2026-02-19 21:00:00
1    2026-02-20 00:00:00
2    2026-02-20 03:00:00
3    2026-02-20 06:00:00
4    2026-02-20 09:00:00
5    2026-02-20 12:00:00
6    2026-02-20 15:00:00
7    2026-02-20 18:00:00
8    2026-02-20 21:00:00
9    2026-02-21 00:00:00
10   2026-02-21 03:00:00
11   2026-02-21 06:00:00
12   2026-02-21 09:00:00
13   2026-02-21 12:00:00
14   2026-02-21 15:00:00
15   2026-02-21 18:00:00
16   2026-02-21 21:00:00
17   2026-02-22 00:00:00
18   2026-02-22 03:00:00
19   2026-02-22 06:00:00
20   2026-02-22 09:00:00
21   2026-02-22 12:00:00
22   2026-02-22 15:00:00
23   2026-02-22 18:00:00
24   2026-02-22 21:00:00
25   2026-02-23 00:00:00
26   2026-02-23 03:00:00
27   2026-02-23 06:00:00
28   2026-02-23 09:00:00
29   2026-02-23 12:00:00
30   2026-02-23 15:00:00
31   2026-02-23 18:00:00
32   2026-02-23 21:00:00
33   2026-02-24 00:00:00
34   2026-02-24 03:00:00
35   2026-02-24 06:00:00
36   2026-02-24 09:00:00
37   2026-02-24 12:00:00
38   2026-02-24 15:00:00
39   2026-02-24 18:00:00
Name: dt_txt, dtype: datetime64[ns]

In [257]:
df['date'] = df['dt_txt'].dt.date
df['time'] = df['dt_txt'].dt.time

# dropping useless features

df = df.drop(columns=['Unnamed: 0', 'dt', 'dt_txt'])


df.head(5)

,summery,probability_of_precipitation_unit(%),temprature_unit(K),pressure_unit(hPa),sea_level_pressure_unit(hPa),ground_level_pressure_unit(hPa),humidity_unit(%),cloudiness_unit(%),speed,degrees,direction,gust_speed_unit(meter/sec),part_of_day,visibility_distance,date,time
0,"overcast clouds, 277.99K, feels like 275.27K, ...",0,277.99,1010,1010,1008,90,100,3.27,300,West-Northwest,7.62,night,10000.0,2026-02-19,21:00:00
1,"overcast clouds, 277.71K, feels like 275.03K, ...",0,277.71,1013,1013,1011,87,100,3.13,276,West,7.62,night,10000.0,2026-02-20,00:00:00
2,"overcast clouds, 277.42K, feels like 274.89K, ...",0,277.42,1017,1017,1012,87,100,2.86,248,West-Southwest,8.56,night,10000.0,2026-02-20,03:00:00
3,"overcast clouds, 278.79K, feels like 276.37K, ...",0,278.79,1018,1018,1013,89,100,3.08,229,Southwest,9.26,night,10000.0,2026-02-20,06:00:00
4,"overcast clouds, 279.68K, feels like 276.84K, ...",0,279.68,1018,1018,1014,80,100,4.09,218,Southwest,11.92,day,10000.0,2026-02-20,09:00:00

In [258]:
df.describe()

,probability_of_precipitation_unit(%),temprature_unit(K),pressure_unit(hPa),sea_level_pressure_unit(hPa),ground_level_pressure_unit(hPa),humidity_unit(%),cloudiness_unit(%),speed,degrees,gust_speed_unit(meter/sec),visibility_distance
count,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000,40.000000,40.000000,40.000000,40.0
mean,12.700000,283.240250,1017.300000,1017.300000,1012.95000,83.175000,91.200000,5.150250,238.850000,12.443500,10000.0
std,30.322371,2.542499,2.162619,2.162619,1.82504,9.091804,17.701514,1.072724,17.829031,1.815346,0.0
min,0.000000,277.420000,1010.000000,1010.000000,1008.00000,63.000000,26.000000,2.860000,203.000000,7.620000,10000.0
25%,0.000000,281.602500,1016.000000,1016.000000,1012.00000,76.750000,94.500000,4.580000,228.750000,11.915000,10000.0
50%,0.000000,284.030000,1018.000000,1018.000000,1013.00000,86.000000,100.000000,5.220000,236.500000,12.765000,10000.0
75%,0.250000,284.817500,1019.000000,1019.000000,1014.00000,91.000000,100.000000,5.795000,248.250000,13.465000,10000.0
max,100.000000,287.460000,1020.000000,1020.000000,1016.00000,95.000000,100.000000,8.050000,300.000000,15.720000,10000.0

In [256]:
# df.columns

df['summery'].to_list()

['overcast clouds, 277.99K, feels like 275.27K, winds 3.27 meter/sec from West-Northwest, 90% humidity',
 'overcast clouds, 277.71K, feels like 275.03K, winds 3.13 meter/sec from West, 87% humidity',
 'overcast clouds, 277.42K, feels like 274.89K, winds 2.86 meter/sec from West-Southwest, 87% humidity',
 'overcast clouds, 278.79K, feels like 276.37K, winds 3.08 meter/sec from Southwest, 89% humidity',
 'overcast clouds, 279.68K, feels like 276.84K, winds 4.09 meter/sec from Southwest, 80% humidity',
 'overcast clouds, 282.97K, feels like 279.97K, winds 6.61 meter/sec from Southwest, 76% humidity',
 'light rain, 282.65K, feels like 279.44K, winds 7.01 meter/sec from Southwest, 91% humidity',
 'light rain, 283.89K, feels like 283.06K, winds 8.05 meter/sec from West-Southwest, 78% humidity',
 'overcast clouds, 281.37K, feels like 278.56K, winds 4.88 meter/sec from West, 87% humidity',
 'overcast clouds, 280.64K, feels like 277.84K, winds 4.46 meter/sec from West-Southwest, 90% humidity',
 'overcast clouds, 280.6K, feels like 277.48K, winds 5.16 meter/sec from West-Southwest, 89% humidity',
 'overcast clouds, 280.84K, feels like 278K, winds 4.65 meter/sec from Southwest, 93% humidity',
 'overcast clouds, 282.98K, feels like 280.52K, winds 5.02 meter/sec from West-Southwest, 92% humidity',
 'overcast clouds, 284.79K, feels like 284.1K, winds 5.19 meter/sec from West-Southwest, 80% humidity',
 'light rain, 285.37K, feels like 285.05K, winds 5.26 meter/sec from Southwest, 92% humidity',
 'overcast clouds, 285.15K, feels like 284.81K, winds 5.58 meter/sec from Southwest, 92% humidity',
 'overcast clouds, 284.77K, feels like 284.36K, winds 5.78 meter/sec from Southwest, 91% humidity',
 'overcast clouds, 284.77K, feels like 284.31K, winds 6.06 meter/sec from Southwest, 89% humidity',
 'light rain, 284.4K, feels like 283.98K, winds 5.67 meter/sec from Southwest, 92% humidity',
 'light rain, 284.17K, feels like 283.73K, winds 5.89 meter/sec from Southwest, 92% humidity',
 'light rain, 284.42K, feels like 283.93K, winds 5.77 meter/sec from West-Southwest, 89% humidity',
 'light rain, 286.67K, feels like 285.83K, winds 5.25 meter/sec from West-Southwest, 67% humidity',
 'broken clouds, 287.07K, feels like 286.16K, winds 5.06 meter/sec from Southwest, 63% humidity',
 'broken clouds, 284.91K, feels like 284.13K, winds 5.55 meter/sec from West-Southwest, 76% humidity',
 'light rain, 283.18K, feels like 282.33K, winds 5.86 meter/sec from West-Southwest, 80% humidity',
 'light rain, 281.98K, feels like 278.82K, winds 6.25 meter/sec from West-Southwest, 80% humidity',
 'scattered clouds, 281.3K, feels like 278.08K, winds 5.91 meter/sec from West-Southwest, 80% humidity',
 'broken clouds, 281.68K, feels like 278.48K, winds 6.12 meter/sec from West, 74% humidity',
 'overcast clouds, 282.64K, feels like 279.83K, winds 5.75 meter/sec from West-Southwest, 71% humidity',
 'overcast clouds, 284.8K, feels like 283.74K, winds 5.84 meter/sec from West-Southwest, 66% humidity',
 'overcast clouds, 286.12K, feels like 285.14K, winds 5.27 meter/sec from West-Southwest, 64% humidity',
 'overcast clouds, 284.38K, feels like 283.54K, winds 4.73 meter/sec from Southwest, 76% humidity',
 'overcast clouds, 283.64K, feels like 282.96K, winds 4.6 meter/sec from Southwest, 85% humidity',
 'overcast clouds, 284.27K, feels like 283.89K, winds 4.52 meter/sec from West-Southwest, 94% humidity',
 'overcast clouds, 284.63K, feels like 284.26K, winds 4.03 meter/sec from Southwest, 93% humidity',
 'broken clouds, 283.44K, feels like 283.01K, winds 3.88 meter/sec from Southwest, 95% humidity',
 'overcast clouds, 284.87K, feels like 284.32K, winds 5.16 meter/sec from Southwest, 85% humidity',
 'overcast clouds, 286.17K, feels like 285.54K, winds 5.47 meter/sec from Southwest, 77% humidity',
 'overcast clouds, 287.46K, feels like 286.8K, winds 5.17 meter/sec from South-Southwest, 71% humidity',
 'broken clouds, 285.03K, feels like 284.47K, winds 4.12 meter/sec from South-Southwest, 84% humidity']