# **Multi-class classification matrix**

In 27_0 we learned how to deal with binary classification problems. Like where the output value is either 0 or 1. Now we will learn how to deal with multi-class classification problems. Like where the output value can be more than 2 values.

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report

import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv('iris_dataset.csv')
print(df['species'].nunique())
print(df['species'].unique())
df.head()

3
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

   Id  sepal_length  sepal_width  petal_length  petal_width      species
0   1           5.1          3.5           1.4          0.2  Iris-setosa
1   2           4.9          3.0           1.4          0.2  Iris-setosa
2   3           4.7          3.2           1.3          0.2  Iris-setosa
3   4           4.6          3.1           1.5          0.2  Iris-setosa
4   5           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('species', axis=1), df['species'], test_size=0.2, random_state=2)

# now we will be comparing the predictions of logistic reg and decision tree classifier
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

clf1.fit(X_train, y_train)
y_pred1 = clf1.predict(X_test)

clf2.fit(X_train, y_train)
y_pred2 = clf2.predict(X_test)

In [ ]:
def prt(y_test, y_pred, model_name):
    print(f"{model_name}")
    print(accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print()


prt(y_test, y_pred1, 'LOGISTIC REGRESSION')
prt(y_test, y_pred2, 'DECISION TREE')

# as we can see both the models are giving the same accuracy

LOGISTIC REGRESSION
1.0
[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]

DECISION TREE
1.0
[[14  0  0]
 [ 0  8  0]
 [ 0  0  8]]

In [ ]:
pd.DataFrame(confusion_matrix(y_test, y_pred1), columns=list(range(0,3)))   # this is how we print confusion matrix in a data frame format

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8